version: '3'

services:
  - type: web
    name: dxquizbot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
    disk:
      name: data
      mountPath: /usr/src/app/data
      sizeGB: 1